### ISSUE TITLE
Create activity for 2. Writing for the Web: Composing [CSS]

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#113]
#111 is covering the learning objectives, and this ticket is for the CSS activity. See also #112 

 In the original meta arc I made these suggestions for Composing (but perhaps the community wants to discuss / share what they've got?)

**Writing for the Web: Composing CSS** (45 mins) This unit helps learners start to add style to their webpages.
* (5 mins) Introduction round
* (10 mins) Let’s write CSS. Facilitator explains CSS, including tag styles, ids and classes, while learners follow along writing on their first webpage: [Chad's writeup](https://docs.google.com/document/d/19yoUUau3yIyEGNe56V70fo7xE1T7lcR4MP1Ow41e3lo/edit?token=AC4w5VgTbfYzUDzC5Ervmgu8YZn3AsUlWA:1404326680537&skipDomain=false)
* (30 mins) [Stuck in the 90s](https://mozteach.makes.org/thimble/principles-of-design-page-elements)

**Comment by dajbelshaw** [comment]
Does this activity depend upon **Writing for the Web: Composing HTML**? Do learners *have* to add CSS to something they've already created? Should we include an option for those who may have missed that session?

**Comment by LauraHilliger** [comment]
We should try to make them standalone. A tiny bit of CSS in the HTML and a tiny bit of HTML in the CSS session. Could try to do that by having the HTML session use a few inline styles, and the CSS session having a basic webpage structure. I think it's about where we put the weight.

**Comment by dajbelshaw** [comment]
Cool. We could even just have an external stylesheet like [Makerstrap](http://mozilla.github.io/makerstrap/demo/#/) or [purecss.io](http://purecss.io) to get out their way for the HTML activity.

**Comment by dajbelshaw** [comment]
OK, so I think we may need to rescope this one for a couple of reasons:

1. CSS isn't in **Composing for the Web** - it's currently in **Designing for the Web**
2. If we go with the [structure proposed](https://github.com/mozilla/webmaker-curriculum/issues/97#issuecomment-71462534) in Issue #97 then CSS wouldn't come until WebLit Basics II. 

Of course, we could always switch **Remixing** and **Designing for the Web** which would kind of solve this. 

So, a couple of options:

A) Switch around proposed curriculum roadmap so that this fits under **Designing for the Web** in Web Literacy Basics I
B) Punt this to Web Literacy Basics II and put a **Remixing** activity in here instead

Thoughts? :)

**Comment by dajbelshaw** [comment]
Closing this as we're going with Remixing for Web Literacy Basics I.
